backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend:
  url: http://localhost:8081/api/v1

site_url: https://cucumbercms.netlify.app
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    delete: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    folder: "content/settings"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Bollean", name: "draft", widget: "boolean", default: true }
      - { label: "Code", name: "code", widget: "code" }
      - { label: "Color", name: "color", widget: "color" }
      - label: "Birthdate"
        name: "birthdate"
        widget: "date"
        default: ""
        format: "MMM Do YY"
      - label: "Start time"
        name: "start"
        widget: "datetime"
        default: ""
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
        format: "LLL"
        picker_utc: false
      - label: "Manual PDF"
        name: "manual_pdf"
        widget: "file"
        default: "/uploads/general-manual.pdf"
        media_library:
          config:
            multiple: true
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        default: "/uploads/chocolate-dogecoin.jpg"
        media_library:
          config:
            multiple: true
      - label: "Testimonials"
        name: "testimonials"
        minimize_collapsed: true
        widget: "list"
        fields:
          - {
              label: Quote,
              name: quote,
              widget: string,
              default: "Everything is awesome!",
            }
          - { label: Author, name: author, widget: string }
      - { label: "Location", name: "location", widget: "map" }
      - { label: "Blog post content", name: "body", widget: "markdown" }
      - label: "Puppy Count"
        name: "puppies"
        widget: "number"
        default: 2
        value_type: "int"
        min: 1
        max: 101
        step: 2
      - label: "Profile"
        name: "profile"
        widget: "object"
        summary: "{{fields.name}}: {{fields.birthdate}}"
        fields:
          - {
              label: "Public",
              name: "public",
              widget: "boolean",
              default: true,
            }
          - { label: "Name", name: "name", widget: "string" }
          - label: "Birthdate"
            name: "birthdate"
            widget: "date"
            default: ""
            format: "MM/DD/YYYY"
          - label: "Address"
            name: "address"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Street Address", name: "street", widget: "string" }
              - { label: "City", name: "city", widget: "string" }
              - { label: "Postal Code", name: "post-code", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        max: 3
        options: ["Design", "UX", "Dev"]
        default: ["Design"]
      - { label: "Title", name: "title", widget: "string" }
  - name: "products"
    label: "Products"
    folder: "_products"
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Price", name: "price", widget: "number" }
      - { label: "SKU", name: "sku", widget: "string" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Body", name: "body", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "productdetails",
        }
