backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend:
  url: http://localhost:8081/api/v1

site_url: https://cucumbercms.netlify.app
media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: "page"
    label: "Page"
    folder: "content/_pages/page"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "My Custom Widget", name: "mywidgetname", widget: "mywidget" }

  - name: "widget_docs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Widget Docs" # Used in the UI, ie.: "New Post"
    folder: "website/content/docs/widgets" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Name", name: "title" }
      - { label: "Label", name: "label" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "website/content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Description (for blog list)",
          name: "description",
          widget: "text",
        }
      - {
          label: "Meta Description (defaults to Description)",
          name: "meta_description",
          widget: "text",
          required: false,
        }
      - { label: "Twitter Image", name: "twitter_image", widget: "image" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: updates
    label: Updates
    files:
      - name: releases
        label: Releases
        file: website/data/updates.yml
        fields:
          - name: updates
            label: Releases
            widget: list
            fields:
              - { name: version, label: Version }
              - { name: date, label: Date, widget: date }
              - { name: description, label: Description }
      - name: notifications
        label: Notifications
        file: website/data/notifications.yml
        description: Site-top notifications - publish one at a time
        fields:
          - name: notifications
            label: Notifications
            widget: list
            fields:
              - { label: Title, name: title, widget: string, tagname: h1 }
              - { label: Published, name: published, widget: boolean }
              - { label: Loud, name: loud, widget: boolean }
              - { label: Message, name: message, widget: text }
              - { label: URL, name: url }
